import { Inter, Cairo } from "next/font/google";
import "../globals.css";
import TransitionProvider from "./components/transitionProvider";
import Head from "next/head";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["arabic"], weight: "500" });
export const metadata = {
  title: "Squadron Link",
  description: "Generated by create next app",
};
async function RootLayout({ children }) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={`${
            locale === "ar" ? cairo.className : inter.className
          } bg-gradient-to-b to-red-50  from-blue-100  dark:from-black dark:to-slate-900`}
        >
          <NextIntlClientProvider messages={messages}>
            <TransitionProvider inter={inter}>{children}</TransitionProvider>
          </NextIntlClientProvider>
          <Toaster />
        </body>
      </ThemeProvider>
    </html>
  );
}
export default RootLayout;
