import { Inter, Cairo } from "next/font/google";
import "../globals.css";
import TransitionProvider from "./components/transitionProvider";
import Head from "next/head";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["arabic"], weight: "500" });
export const metadata = {
  title: "Squadron Link",
  description: "Generated by create next app",
};
async function RootLayout({ children }) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${
          locale === "en" ? cairo.className : cairo.className
        } bg-gradient-to-b to-red-50  from-blue-100  `}
      >
        <NextIntlClientProvider messages={messages}>
          <TransitionProvider inter={inter}>{children}</TransitionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
export default RootLayout;
